AWSTemplateFormatVersion: 2010-09-09
Description: Abbas template to create ec2 instance
Resources:
  mySecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: allow http traffic port 80
      GroupName: allow http
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      VpcId: "vpc-065b24e8c1e8eb2bd"
  myEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0cff7528ff583bf9a"
      InstanceType: t3.micro
      KeyName: "abbas-root2"
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        GroupSet: 
          - Ref: "mySecGroup"
        SubnetId: "subnet-0a968701b478bd332"
      UserData:
       Fn::Base64: !Sub |
         #!/bin/bash
         sudo yum update -y
         sudo yum install -y httpd
         sudo systemctl start httpd
         sudo systemctl enable httpd
